### PR TITLE
Create Position Prompt Screen

### LINKED ISSUE #11: Ask for Position
Prompt user for position (Red1, Red2, Red3, Blue1, Blue2, Blue3) and save it to shared_preferences when done.

### PR DESCRIPTION
**Pull request by Cal-Hagner**
Potentially resolves #11.

### CODE REVIEW

**Comment by Cal-Hagner** [comment]
Order of the setup navigation buttons is as it is for debugging/testing purposes. The actual order is something we have yet to determine, and is subject to change.

**Comment by Cal-Hagner** [comment]
Radio Buttons seemed to be the kind of thing we're looking for, so I used them. Not totally sure if I implemented shared_preferences correctly, and the styling is a bit wonky (had to center everything because the row was screwing with the column).

**Comment by Cal-Hagner** [comment]
Screenshot_1587165126

**Review by gleich — APPROVED** [review]
👍 LGTM

**Pull request merged**
